b abort
b mos_error
#b GC_init
#b GC_malloc
#b GC_free
#b _mos_mf_defaultBehavior__loadFile_
b _mos_mf_bcMethod_decompile
#b _mos_completion_generator
#b _mos_bcMethod_run
#b _mos_mf_exprSlot_compile_
#b _mos_mf_exprReadOnlySlot_compile_
#b _mos_mf_defaultBehavior__addMethodSlot_Value_
#b mos_exprBlock
#b mos_exprMethod
#b _mos_CATCH_BEGIN
#b _mos_CATCH_END
#b _mos_mf_bcMethod___applyMethod_
b mos_THROW
#b bcMethod.c:335
#b _mos_parseFromStream
